# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: phone_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='phone_service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13phone_service.proto\"\"\n\x11\x43heckPhoneRequest\x12\r\n\x05phone\x18\x01 \x01(\t\"$\n\x12\x43heckPhoneResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x32\x45\n\x0cPhoneService\x12\x35\n\nCheckPhone\x12\x12.CheckPhoneRequest\x1a\x13.CheckPhoneResponseb\x06proto3'
)




_CHECKPHONEREQUEST = _descriptor.Descriptor(
  name='CheckPhoneRequest',
  full_name='CheckPhoneRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='phone', full_name='CheckPhoneRequest.phone', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=57,
)


_CHECKPHONERESPONSE = _descriptor.Descriptor(
  name='CheckPhoneResponse',
  full_name='CheckPhoneResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='exists', full_name='CheckPhoneResponse.exists', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=95,
)

DESCRIPTOR.message_types_by_name['CheckPhoneRequest'] = _CHECKPHONEREQUEST
DESCRIPTOR.message_types_by_name['CheckPhoneResponse'] = _CHECKPHONERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CheckPhoneRequest = _reflection.GeneratedProtocolMessageType('CheckPhoneRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKPHONEREQUEST,
  '__module__' : 'phone_service_pb2'
  # @@protoc_insertion_point(class_scope:CheckPhoneRequest)
  })
_sym_db.RegisterMessage(CheckPhoneRequest)

CheckPhoneResponse = _reflection.GeneratedProtocolMessageType('CheckPhoneResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHECKPHONERESPONSE,
  '__module__' : 'phone_service_pb2'
  # @@protoc_insertion_point(class_scope:CheckPhoneResponse)
  })
_sym_db.RegisterMessage(CheckPhoneResponse)



_PHONESERVICE = _descriptor.ServiceDescriptor(
  name='PhoneService',
  full_name='PhoneService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=97,
  serialized_end=166,
  methods=[
  _descriptor.MethodDescriptor(
    name='CheckPhone',
    full_name='PhoneService.CheckPhone',
    index=0,
    containing_service=None,
    input_type=_CHECKPHONEREQUEST,
    output_type=_CHECKPHONERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PHONESERVICE)

DESCRIPTOR.services_by_name['PhoneService'] = _PHONESERVICE

# @@protoc_insertion_point(module_scope)
